input.onButtonPressed(Button.A, function () {
    basic.clearScreen()
    for (let x = 0; x <= 0; x++) {
        led.plot(2, 2)
        basic.pause(100)
        led.plot(2, 3)
        basic.pause(100)
        led.plot(1, 3)
        basic.pause(100)
        led.plot(1, 2)
        basic.pause(100)
        led.plot(1, 1)
        basic.pause(100)
        led.plot(2, 1)
        basic.pause(100)
        led.plot(3, 1)
        basic.pause(100)
        led.plot(3, 2)
        basic.pause(100)
        led.plot(3, 3)
        basic.pause(100)
        led.plot(3, 4)
        basic.pause(100)
        led.plot(2, 4)
        basic.pause(100)
        led.plot(1, 4)
        basic.pause(100)
        led.plot(0, 4)
        basic.pause(100)
        led.plot(0, 3)
        basic.pause(100)
        led.plot(0, 2)
        basic.pause(100)
        led.plot(0, 1)
        basic.pause(100)
        led.plot(0, 0)
        basic.pause(100)
        led.plot(1, 0)
        basic.pause(100)
        led.plot(2, 0)
        basic.pause(100)
        led.plot(3, 0)
        basic.pause(100)
        led.plot(4, 0)
        basic.pause(100)
        led.plot(4, 1)
        basic.pause(100)
        led.plot(4, 2)
        basic.pause(100)
        led.plot(4, 3)
        basic.pause(100)
        led.plot(4, 4)
        basic.pause(100)
        led.unplot(2, 2)
        basic.pause(100)
        led.unplot(2, 3)
        basic.pause(100)
        led.unplot(1, 3)
        basic.pause(100)
        led.unplot(1, 2)
        basic.pause(100)
        led.unplot(1, 1)
        basic.pause(100)
        led.unplot(2, 1)
        basic.pause(100)
        led.unplot(3, 1)
        basic.pause(100)
        led.unplot(3, 2)
        basic.pause(100)
        led.unplot(3, 3)
        basic.pause(100)
        led.unplot(3, 4)
        basic.pause(100)
        led.unplot(2, 4)
        basic.pause(100)
        led.unplot(1, 4)
        basic.pause(100)
        led.unplot(0, 4)
        basic.pause(100)
        led.unplot(0, 3)
        basic.pause(100)
        led.unplot(0, 2)
        basic.pause(100)
        led.unplot(0, 1)
        basic.pause(100)
        led.unplot(0, 0)
        basic.pause(100)
        led.unplot(1, 0)
        basic.pause(100)
        led.unplot(2, 0)
        basic.pause(100)
        led.unplot(3, 0)
        basic.pause(100)
        led.unplot(4, 0)
        basic.pause(100)
        led.unplot(4, 1)
        basic.pause(100)
        led.unplot(4, 2)
        basic.pause(100)
        led.unplot(4, 3)
        basic.pause(100)
        led.unplot(4, 4)
    }
})
input.onButtonPressed(Button.AB, function () {
    basic.clearScreen()
    for (let x = 0; x <= 0; x++) {
        led.plot(4, 4)
        basic.pause(100)
        led.plot(4, 3)
        basic.pause(100)
        led.plot(4, 2)
        basic.pause(100)
        led.plot(4, 1)
        basic.pause(100)
        led.plot(4, 0)
        basic.pause(100)
        led.plot(3, 0)
        basic.pause(100)
        led.plot(2, 0)
        basic.pause(100)
        led.plot(1, 0)
        basic.pause(100)
        led.plot(0, 0)
        basic.pause(100)
        led.plot(0, 1)
        basic.pause(100)
        led.plot(0, 2)
        basic.pause(100)
        led.plot(0, 3)
        basic.pause(100)
        led.plot(0, 4)
        basic.pause(100)
        led.plot(1, 4)
        basic.pause(100)
        led.plot(2, 4)
        basic.pause(100)
        led.plot(3, 4)
        basic.pause(100)
        led.plot(3, 3)
        basic.pause(100)
        led.plot(3, 2)
        basic.pause(100)
        led.plot(3, 1)
        basic.pause(100)
        led.plot(2, 1)
        basic.pause(100)
        led.plot(1, 1)
        basic.pause(100)
        led.plot(1, 2)
        basic.pause(100)
        led.plot(1, 3)
        basic.pause(100)
        led.plot(2, 3)
        basic.pause(100)
        led.plot(2, 2)
    }
})
input.onButtonPressed(Button.B, function () {
    basic.clearScreen()
    for (let x = 0; x <= 0; x++) {
        led.plot(4, 4)
        basic.pause(100)
        led.plot(4, 3)
        basic.pause(100)
        led.plot(4, 2)
        basic.pause(100)
        led.plot(4, 1)
        basic.pause(100)
        led.plot(4, 0)
        basic.pause(100)
        led.plot(3, 0)
        basic.pause(100)
        led.plot(2, 0)
        basic.pause(100)
        led.plot(1, 0)
        basic.pause(100)
        led.plot(0, 0)
        basic.pause(100)
        led.plot(0, 1)
        basic.pause(100)
        led.plot(0, 2)
        basic.pause(100)
        led.plot(0, 3)
        basic.pause(100)
        led.plot(0, 4)
        basic.pause(100)
        led.plot(1, 4)
        basic.pause(100)
        led.plot(2, 4)
        basic.pause(100)
        led.plot(3, 4)
        basic.pause(100)
        led.plot(3, 3)
        basic.pause(100)
        led.plot(3, 2)
        basic.pause(100)
        led.plot(3, 1)
        basic.pause(100)
        led.plot(2, 1)
        basic.pause(100)
        led.plot(1, 1)
        basic.pause(100)
        led.plot(1, 2)
        basic.pause(100)
        led.plot(1, 3)
        basic.pause(100)
        led.plot(2, 3)
        basic.pause(100)
        led.plot(2, 2)
        basic.pause(100)
        led.unplot(4, 4)
        basic.pause(100)
        led.unplot(4, 3)
        basic.pause(100)
        led.unplot(4, 2)
        basic.pause(100)
        led.unplot(4, 1)
        basic.pause(100)
        led.unplot(4, 0)
        basic.pause(100)
        led.unplot(3, 0)
        basic.pause(100)
        led.unplot(2, 0)
        basic.pause(100)
        led.unplot(1, 0)
        basic.pause(100)
        led.unplot(0, 0)
        basic.pause(100)
        led.unplot(0, 1)
        basic.pause(100)
        led.unplot(0, 2)
        basic.pause(100)
        led.unplot(0, 3)
        basic.pause(100)
        led.unplot(0, 4)
        basic.pause(100)
        led.unplot(1, 4)
        basic.pause(100)
        led.unplot(2, 4)
        basic.pause(100)
        led.unplot(3, 4)
        basic.pause(100)
        led.unplot(3, 3)
        basic.pause(100)
        led.unplot(3, 2)
        basic.pause(100)
        led.unplot(3, 1)
        basic.pause(100)
        led.unplot(2, 1)
        basic.pause(100)
        led.unplot(1, 1)
        basic.pause(100)
        led.unplot(1, 2)
        basic.pause(100)
        led.unplot(1, 3)
        basic.pause(100)
        led.unplot(2, 3)
        basic.pause(100)
        led.unplot(2, 2)
    }
})
basic.showIcon(IconNames.Heart)
